### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Tommie1236** [Tommie1236/midi-controller#5]
- [ ] #6
- [ ] (main) add sub fader board connections
- [ ] (usb) add over current sense and power switch to external usb ports
- [ ] (usb) how connect shield to gnd?
- [ ] (midi) figure out what to do with footswiches/pedal
- [ ] (fader) move display and drive circuitry to 4xx pcb, change all references in schematic/pcb
- [ ] (fader) add display backlight drivers
- [ ] (fader) add mainboard connections
- [ ] (fader) pca 9635 (u306) i2c address
- [ ] (fader) bank/bpm display connections
- [ ] (fader) update fader-encoder connections (add display dc line)
- [ ] (fader) finish routing top pcb, mainly spi bus
- [ ] (fader) how drive encoder dot leds? 
- [ ] #8
- [x] #7
